# Generated by Django 3.2.9 on 2021-11-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('uniqueid', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('lga_id', models.IntegerField(max_length=50)),
                ('lga_name', models.CharField(max_length=50)),
                ('state_id', models.IntegerField(max_length=50)),
                ('lga_description', models.CharField(max_length=50)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('uniqueid', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('polling_unit_id', models.IntegerField(max_length=50)),
                ('ward_id', models.IntegerField(max_length=50)),
                ('lga_id', models.IntegerField(max_length=50)),
                ('uniquewardid', models.IntegerField(max_length=50)),
                ('polling_unit_number', models.CharField(max_length=50)),
                ('polling_unit_name', models.CharField(max_length=50)),
                ('polling_unit_description', models.CharField(max_length=50)),
                ('lat', models.FloatField(max_length=50)),
                ('long', models.FloatField(max_length=50)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PollingUnitResult',
            fields=[
                ('result_id', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('polling_unit_uniqueid', models.IntegerField(max_length=50)),
                ('party_abbreviation', models.CharField(max_length=50)),
                ('party_score', models.IntegerField(max_length=50)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('uniqueid', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('ward_id', models.IntegerField(max_length=50)),
                ('ward_name', models.CharField(max_length=50)),
                ('lga_id', models.IntegerField(max_length=50)),
                ('ward_description', models.CharField(max_length=50)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
        ),
    ]
