# Generated by Django 3.2.9 on 2021-11-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='date_entered',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='date_entered',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pollingunitresult',
            name='date_entered',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ward',
            name='date_entered',
            field=models.CharField(max_length=50),
        ),
    ]
