# Generated by Django 3.2.9 on 2021-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211104_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='date_entered',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='entered_by_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='lat',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='long',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='user_ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
