# Generated by Django 3.2.9 on 2021-11-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211104_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunitresult',
            name='date_entered',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunitresult',
            name='entered_by_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunitresult',
            name='user_ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
